src/pytho_quiz/pytho_quiz/urls.py
from django.conf.urls import url
from django.contrib import admin
from quiz_app import urls ,views
#from quiz import urls
from django.conf.urls import include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^quiz_app/',include('quiz_app.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^logout',views.user_logout,name='loggedout'),
    url(r'^sample',views.sample)
]

urlpatterns += staticfiles_urlpatterns()

src/pytho_quiz/quiz_app/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'quiz_app'
urlpatterns = [
    url(r'homepage/$',views.homepageview,name='homepage'),
    url(r'register/$',views.register,name='register'),
    url(r'login/$',views.user_login,name='login'),
    url(r'logout/$',views.user_logout,name='logout'),
    #url(r'question/$',views.question_view,name='question'),
    url(r'about/$',views.about,name='about'),
    url(r'contact/$',views.contact,name='contact'),
    url(r'questions/(?P<pk>[0-9]{1})/$',views.question_detail_view,name='quedetail'),

]

src/pytho_quiz/quiz_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Quizquestion(models.Model):
    q_name = models.CharField(max_length=200)
    opt1 = models.CharField(max_length=100)
    opt2 = models.CharField(max_length=100)
    opt3 = models.CharField(max_length=100)
    opt4 = models.CharField(max_length=100)
    answer = models.CharField(max_length=100)
    created_time = models.DateTimeField(auto_now_add=True)
    q_id = models.IntegerField()

    def __str__(self):
        return self.q_name

class Sample(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

src/pytho_quiz/quiz_app/forms.py
from django import forms
from django.contrib.auth.models import User

class UserRegistrationfrom(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username','email','password')

src/pytho_quiz/quiz_app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render , reverse , get_object_or_404
from django.shortcuts import HttpResponse , HttpResponseRedirect
from .forms import UserRegistrationfrom
from django.contrib.auth import login , authenticate , logout
from django.contrib.auth.decorators import login_required
from quiz_app.models import Sample , Quizquestion

# Create your views here.
def homepageview(request):
    my_dic = {'insert':'Hello'}
    return render(request,'quiz_app/homepage.html',context=my_dic)

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserRegistrationfrom(data=request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            registered = True
        else:
            print(user_form.errors)
    else:
        user_form = UserRegistrationfrom()
    return render(request,'quiz_app/register.html',{'user_form':user_form,
                                                    'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('quiz_app:homepage'))
            else:
                return HttpResponse('account not active')
        else:
            return HttpResponse('invalid login details')
    else:
        return render(request,'quiz_app/login.html')



    return render(request,'quiz_app/login.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('quiz_app:homepage'))

@login_required
def question_view(request):
    product = Quizquestion.objects.all()
    correct_ans = Quizquestion.objects.get(id=2)
    my_dic = {'question':product}
    if request.method == 'POST':
        user_answer = request.POST.get('option')
        print(user_answer)
        if user_answer == correct_ans.answer:

            my_dict = {'message':'Congratulation, your answer is right',
            'right_ans':correct_ans.answer,
            'user_ans':user_answer,
            'question':product}
            return render(request,'quiz_app/question.html',context=my_dict)
        else:
            my_dict = {'message':'Oops!, your answer is Wrong',
            'right_ans':correct_ans.answer,
            'user_ans':user_answer,
            'question':product}
            return render(request,'quiz_app/question.html',context=my_dict)

    return render(request,'quiz_app/question.html',context=my_dic)

def sample(request):
    product = Sample.objects.all()
    my_dict = {'objects':product}
    return render(request,'sample.html',context=my_dict)

def about(request):
    return render(request,'quiz_app/about.html')

def contact(request):
    return render(request,'quiz_app/contact.html')

def question_detail_view(request,pk=1 , *args , **kwargs):
    product = Quizquestion.objects.get(id=pk)
    my_dict = {'question': product}
    print(product.q_name)
    print(product.id)
    return render(request,'quiz_app/detail_question.html',context=my_dict)

src/pytho_quiz/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>


{% url 'quiz_app:homepage' as homepage_url %}
{% url 'quiz_app:login' as login_url %}
{% url 'quiz_app:register' as register_url %}
{% url 'quiz_app:question' as question_url %}
{% url 'loggedout' as logout_url %}
{% url 'quiz_app:about' as about_url %}
{% url 'quiz_app:contact' as contact_url %}
{% url 'quiz_app:quedetail' as quedetail_url %}

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <link  href="{% static 'quiz_app/css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous"/>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
     <div class="container">
       <a class="navbar-brand" href="{% url 'quiz_app:homepage' %}" style="font-style: italic;">Python Quiz</a>
       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
       </button>
       <div class="collapse navbar-collapse" id="navbarResponsive">
         <ul class="navbar-nav ml-auto">
           <li class="nav-item {% if request.path == homepage_url %} active{% endif %}">
             <a class="nav-link" href="{% url 'quiz_app:homepage' %}">Home
             </a>
           </li>
           <li class="nav-item {% if request.path == about_url %} active{% endif %}">
             <a class="nav-link" href="{% url 'quiz_app:about' %}">About</a>
           </li>
           <li class="nav-item {% if request.path == contact_url %} active{% endif %}">
             <a class="nav-link" href="{% url 'quiz_app:contact' %}">Contact</a>
           </li>
           {% if request.user.is_authenticated %}
           <li class="nav-item {% if request.path == quedetail_url %} active{% endif %}">
             <a class="nav-link" href="{% url 'quiz_app:quedetail' 2 %}">Test</a>
           </li>
           <li class="nav-item {% if request.path == logout_url %} active{% endif %}">
             <a class="nav-link" href="{% url 'loggedout' %}">Logout</a>
           </li>
           {% else %}
           <li class="nav-item {% if request.path == register_url %} active{% endif %}">
             <a class="nav-link" href="{% url 'quiz_app:register' %}">Register</a>
           </li>
           <li class="nav-item {% if request.path == login_url %} active{% endif %}">
             <a class="nav-link" href="{% url 'quiz_app:login' %}">Login</a>
           </li>
           {% endif %}
         </ul>
       </div>
     </div>
   </nav>

    {% block content %}
    {% endblock %}

  </body>
</html>

src/pytho_quiz/templates/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>hi</h1>
  </body>
</html>

src/pytho_quiz/templates/quiz_app/about.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <h1>Welcome to About page</h1>

</div>
{% endblock %}

src/pytho_quiz/templates/quiz_app/contact.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <h1>Welcome to contact page</h1>

</div>
{% endblock %}

src/pytho_quiz/templates/quiz_app/detail_question.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  {{ question.q_name }}
  <div class="container">
    <ol>
      <form method="post">
        {% csrf_token %}
        <li><input type="radio" name="option" value="{{ question.opt1 }}">{{ question.opt1 }}</li><br>
        <li><input type="radio" name="option" value="{{ question.opt2 }}">{{ question.opt2 }}</li><br>
        <li><input type="radio" name="option" value="{{ question.opt3 }}">{{ question.opt3 }}</li><br>
        <li><input type="radio" name="option" value="{{ question.opt4 }}">{{ question.opt4 }}</li><br>
        <input type="submit" name="" value="submit">
      </form>
    </ol>

  </div>

</div>
<div class="container">
  <h6>Jump to question no.</h6>
    <table>
      <tr>
        <td><a href="{% url 'quiz_app:quedetail' 2 %}">1</a></td>
        <td  id='jump_to_ques'><a href="{% url 'quiz_app:quedetail' 3 %}">2</a></td>
        <td id='jump_to_ques'><a href="{% url 'quiz_app:quedetail' 4 %}">3</a></td>
        <td id='jump_to_ques'><a href="{% url 'quiz_app:quedetail' 5 %}">4</a></td>
        <td id='jump_to_ques'><a href="{% url 'quiz_app:quedetail' 6 %}">5</a></td>
        <td id='jump_to_ques'><a href="{% url 'quiz_app:quedetail' 7 %}">6</a></td>
        <td id='jump_to_ques'><a href="{% url 'quiz_app:quedetail' 8 %}">7</a></td>
        <td id='jump_to_ques'><a href="{% url 'quiz_app:quedetail' 9 %}">8</a></td>
      </tr>
    </table>
</div>

{% endblock %}

src/pytho_quiz/templates/quiz_app/homepage.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class="container">
<h1>Welcome to homepage</h1>
</div>

{% endblock %}

src/pytho_quiz/templates/quiz_app/login.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Bootstrap Sign in Form with Icons</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style type="text/css">
	.login-form {
		width: 340px;
		margin: 50px auto;
	}
    .login-form form {
    	margin-bottom: 15px;
        background: #f7f7f7;
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        padding: 30px;
    }
    .login-form h2 {
        margin: 0 0 15px;
    }
    .form-control, .btn {
        min-height: 38px;
        border-radius: 2px;
    }
	.input-group-addon .fa {
        font-size: 18px;
    }
    .btn {
        font-size: 15px;
        font-weight: bold;
    }
</style>
</head>
<body>
<div class="login-form">
    <form action="{% url 'quiz_app:login' %}" method="post">
      {% csrf_token %}
        <h2 class="text-center">Sign In</h2>
        <div class="form-group">
        	<div class="input-group">
                <span class="input-group-addon"><i class="fa fa-user"></i></span>
                <input type="text" class="form-control" name="username" placeholder="Username" required="required">
            </div>
        </div>
		<div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                <input type="password" class="form-control" name='password' placeholder="Password" required="required">
            </div>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block">Log in</button>
        </div>
        <div class="clearfix">
            <label class="pull-left checkbox-inline"><input type="checkbox"> Remember me</label>

        </div>
    </form>
    <p class="text-center small">Don't have an account! <a href="#">Sign up here</a>.</p>
</div>
</body>
</html>
{% endblock %}

src/pytho_quiz/templates/quiz_app/question.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class='container'>
  {% if question %}
    {% for i in question %}
      <div class="container">
          <h6>{{ i.q_name }}</h6>
      </div>
      <div class="container">
        <ol>
          <form method="post">
            {% csrf_token %}
            <li><input type="radio" name="option" value="{{ i.opt1 }}">{{ i.opt1 }}</li><br>
            <li><input type="radio" name="option" value="{{ i.opt2 }}">{{ i.opt2 }}</li><br>
            <li><input type="radio" name="option" value="{{ i.opt3 }}">{{ i.opt3 }}</li><br>
            <li><input type="radio" name="option" value="{{ i.opt4 }}">{{ i.opt4 }}</li><br>
            <input type="submit" name="" value="submit">
          </form>
        </ol>

      </div>
    {% endfor %}
  {% endif %}
  {{ message }}
  <h6>Your respons is: {{ user_ans }}</h6>
  <h6>Correct answer is: {{ right_ans }}</h6>
</div>
<div class="container">
  <h6>Jump to question no.</h6>
    <table>
      <tr>
        <td><a href="#">1</a></td>
        <td  id='jump_to_ques'><a href="#">2</a></td>
        <td id='jump_to_ques'><a href="#">3</a></td>
        <td id='jump_to_ques'><a href="#">4</a></td>
        <td id='jump_to_ques'><a href="#">5</a></td>
        <td id='jump_to_ques'><a href="#">6</a></td>
        <td id='jump_to_ques'><a href="#">7</a></td>
        <td id='jump_to_ques'><a href="#">8</a></td>
        <td id='jump_to_ques'><a href="#">9</a></td>
        <td id='jump_to_ques'><a href="#">10</a></td>
      </tr>
    </table>
</div>

{% endblock %}

src/pytho_quiz/templates/quiz_app/register.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  {% if registered %}
    <h1>ThankU for registering</h1>
  {% else %}
    <h1>Register Here</h1>
    <form method="post">
      {% csrf_token %}
      {{ user_form.as_p }}
      <input type="submit" name="" value="register">

    </form>
    {% endif %}
</div>
{% endblock %}

src/pytho_quiz/templates/sample.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Sample</title>
  </head>
  <body>
    {% if objects %}
      {% for i in objects %}
      {{ i }}
      {% endfor %}
    {% endif %}
  </body>
</html>